package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Configuration management",
}

var configGenerateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate a .env configuration file",
	RunE: func(cmd *cobra.Command, args []string) error {
		force, _ := cmd.Flags().GetBool("force")
		output, _ := cmd.Flags().GetString("output")

		if !force {
			if _, err := os.Stat(output); err == nil {
				return fmt.Errorf("%s already exists. Use --force to overwrite", output)
			}
		}

		secretKey, err := generateKey(32)
		if err != nil {
			return fmt.Errorf("failed to generate secret key: %w", err)
		}

		env := strings.Join([]string{
			"# Press configuration",
			"# Generated by: press config generate",
			"",
			"APP_ENV=production",
			"APP_HOST=localhost",
			"APP_PORT=3000",
			"APP_DEBUG=false",
			"",
			fmt.Sprintf("SECRET_KEY=%s", secretKey),
			"",
			"DB_PATH=./storage/press.db",
			"UPLOADS_DIR=./storage/uploads",
			"THEME_DIR=./themes/freerange",
			"",
		}, "\n")

		if err := os.WriteFile(output, []byte(env), 0600); err != nil {
			return fmt.Errorf("failed to write %s: %w", output, err)
		}

		fmt.Printf("Success: Generated %s with a new secret key.\n", output)
		return nil
	},
}

var secretCmd = &cobra.Command{
	Use:   "secret",
	Short: "Secret key management",
}

var secretGenerateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate a secret key",
	RunE: func(cmd *cobra.Command, args []string) error {
		key, err := generateKey(32)
		if err != nil {
			return fmt.Errorf("failed to generate secret: %w", err)
		}
		fmt.Println(key)
		return nil
	},
}

func generateKey(bytes int) (string, error) {
	b := make([]byte, bytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func init() {
	configGenerateCmd.Flags().Bool("force", false, "overwrite existing .env file")
	configGenerateCmd.Flags().String("output", ".env", "output file path")

	configCmd.AddCommand(configGenerateCmd)
	secretCmd.AddCommand(secretGenerateCmd)
	rootCmd.AddCommand(configCmd, secretCmd)
}
